spring:
  datasource:
    url: jdbc:h2:mem:country_code_db;MODE=PostgreSQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create

country:
  code:
    url: https://en.wikipedia.org/wiki/List_of_country_calling_codes